/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#include "stm32f7xx.h"

#include "rcc.h"
#include "gpio.h"
#include "timer.h"
#include "adc.h"
#include "interrupt.h"
#include "dma.h"

int main(void) {
	// Global interrupt disable
	__disable_irq();

	init_interrupt();
	init_RCC();
	init_GPIO();
	init_dma();
	init_adc();
	init_dac();
	init_timer8();

	// Global interrupt enable
	__enable_irq();

	/* Loop forever */
	for (;;) {
		for (int i = 0; i < 10000000; i++)
			;
		//GPIOD->ODR ^= 1 << 1;
	}
}
